n = input ('digite algo: ')
print(n)
print('qual e o tipo:', type(n))
print(' so tem espaço?:', n.isspace())
print('è um numero ?', n.isnumeric())
print('e alfabetico?', n.isalpha())
print('è alfanumerico ?', n.isalnum())
print('letras maiusculas ?', n.isupper())
print(' letras minusculas?', n.islower())
print('è captalizada?', n.istitle())
